split_dates: ["2018-01-01", "2020-01-01", "2021-01-01", "2022-01-01"]
is_training: 1
model: null
result_file_name: "Top50"
notes: ""
model_name: "StockAttentioner"

# data loader
data: "Dataset_Abs"
root_path: "./data/raw/market/"
broker_path: "./data/raw/broker/"
target: "etl:adj_close"
goal: "max_price"
task_type: "regression"

loss: "ccc"
general_data: 0
general_data_path: "./data/raw/global/global_data.csv"
data_info_path: "./data/info/data_info.json"
broker_info_path: "./data/info/broker_info.json"

# data info
category: "Top50"
pred_len: 30
seq_len: 60
market_features: ["etl:adj_close", "etl:adj_open", "etl:adj_high", "etl:adj_low", "price:成交筆數", "price:成交金額", "foreign_investors_shareholding:全體外資及陸資持股比率", "institutional_investors_trading_summary:外陸資買賣超股數(不含外資自營商)", "institutional_investors_trading_summary:外資自營商買賣超股數", "institutional_investors_trading_summary:自營商買賣超股數(自行買賣)", "institutional_investors_trading_summary:自營商買賣超股數(避險)", "RSI", "SMA", "MACD", "CMO", "ATR", "BBANDS_upper", "BBANDS_mid", "BBANDS_lower"]
global_features: null
broker_topK: 50

concat_market_global: 0

# model
feature_dim: 19
broker_dim: 50
general_dim: 5
hidden_dim: 128
num_layers: 2
broker: 1
log: 0
thresh: null
d_model: 128
use_fft: 0

# optimization
num_workers: 4
train_epochs: 30
batch_size: 32
patience: 3
learning_rate: 0.0001